### ISSUE TITLE
DBをPlanetScaleから移行する

### ISSUE THREAD

**Issue by otaki0413** [otaki0413/YelpCamp-with-Remix#52]
# 完了の定義
- [x] PlanetScaleからKoyeb上のサーバーレスDBへ移行する

# 補足情報

PlanetScaleが4月よりホビープランを廃止するとのこと（下記公式ブログ参照）
> Hobby プランは、2024 年 4 月 8 日に廃止されます。

https://x.com/PlanetScale/status/1765438197981708684?s=20

**Comment by otaki0413** [comment]
やるべきことメモする
- [ ] 既存DB（PlanetScale）上のデータを出力する
- [ ] MySqlで書かれたSQLをPostgresに変換する
- [ ] KoyebのDB（Neon）にSQLを流し込む

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.
